import type { SkillManifest } from "@/types/skill";

// 内置 Skill 清单
export const BUILTIN_SKILLS: SkillManifest[] = [
  {
    id: "ai-chat",
    name: "AI 助手",
    version: "1.0.0",
    description: "智能 AI 对话助手，支持多模型、工具调用",
    icon: "MessageSquare",
    category: "productivity",
    agent: {
      systemPrompt: "你是 AI-Native OS 的智能助手。",
      model: "auto",
      temperature: 0.7,
      maxTokens: 4096,
    },
    ui: {
      component: "AiChat",
      defaultSize: { width: 700, height: 550 },
      minSize: { width: 400, height: 350 },
      singleton: false,
    },
  },
  {
    id: "file-manager",
    name: "文件管理器",
    version: "1.0.0",
    description: "管理你的文件和文档",
    icon: "FolderOpen",
    category: "utility",
    agent: {
      systemPrompt: "你是文件管理助手。",
      model: "auto",
      temperature: 0.3,
      maxTokens: 2048,
    },
    ui: {
      component: "FileManager",
      defaultSize: { width: 900, height: 600 },
      minSize: { width: 600, height: 400 },
      singleton: true,
    },
  },
  {
    id: "settings",
    name: "设置",
    version: "1.0.0",
    description: "系统设置与偏好配置",
    icon: "Settings",
    category: "system",
    agent: {
      systemPrompt: "",
      model: "auto",
      temperature: 0,
      maxTokens: 0,
    },
    ui: {
      component: "Settings",
      defaultSize: { width: 750, height: 550 },
      minSize: { width: 550, height: 400 },
      singleton: true,
    },
  },
  {
    id: "terminal",
    name: "终端",
    version: "1.0.0",
    description: "AI 命令行终端",
    icon: "Terminal",
    category: "development",
    agent: {
      systemPrompt: "你是命令行助手。",
      model: "auto",
      temperature: 0.3,
      maxTokens: 2048,
    },
    ui: {
      component: "Terminal",
      defaultSize: { width: 750, height: 480 },
      minSize: { width: 500, height: 300 },
      singleton: false,
    },
  },
  {
    id: "browser",
    name: "浏览器",
    version: "1.0.0",
    description: "内置网页浏览器，支持 AI 摘要",
    icon: "Globe",
    category: "utility",
    agent: {
      systemPrompt: "你是网页浏览助手。",
      model: "auto",
      temperature: 0.5,
      maxTokens: 4096,
    },
    ui: {
      component: "Browser",
      defaultSize: { width: 1000, height: 700 },
      minSize: { width: 600, height: 400 },
      singleton: false,
    },
  },
  {
    id: "notes",
    name: "笔记",
    version: "1.0.0",
    description: "Markdown 笔记，AI 辅助写作",
    icon: "FileText",
    category: "productivity",
    agent: {
      systemPrompt: "你是写作助手。",
      model: "auto",
      temperature: 0.7,
      maxTokens: 4096,
    },
    ui: {
      component: "Notes",
      defaultSize: { width: 700, height: 550 },
      minSize: { width: 400, height: 300 },
      singleton: false,
    },
  },
  {
    id: "calendar",
    name: "日历",
    version: "1.0.0",
    description: "日程管理与 AI 日程助手",
    icon: "Calendar",
    category: "productivity",
    agent: {
      systemPrompt: "你是日程管理助手。",
      model: "auto",
      temperature: 0.5,
      maxTokens: 2048,
    },
    ui: {
      component: "Calendar",
      defaultSize: { width: 850, height: 600 },
      minSize: { width: 600, height: 450 },
      singleton: true,
    },
  },
];
